[tool.setuptools.packages.find]
where = ["src"]

[project]
name = "on-off-DRL"
version = "0.1"
description = "Offline Reinforcement Learning for Autonomous Driving: An Investigation of Training Settings"
readme = "README.md"
requires-python = "==3.11.5"
dependencies = [
    "numpy==2.3.3",
    "torch==2.8.0",
    "gymnasium==1.2.0",
    "matplotlib==3.10.6",
    "jupyter",
    "sumolib==1.24.0", 
    "traci==1.24.0", 
    "eclipse-sumo==1.26.0",
    "pandas==2.3.2", 
    "seaborn==0.13.2", 
    "tensorboard==2.20.0",
    "h5py==3.14.0",
    "colorama==0.4.6",
    "msgpack-numpy==0.4.8",
    "msgpack==1.1.1",
    "torchvision==0.23.0",
]

[tool.uv]
package = true    # to install project in editable mode

